### ISSUE TITLE
high vram usage on linux compared to windows vulkan.MemoryAllocator

### ISSUE THREAD

**Issue by EtereosDawn** [KhronosGroup/Vulkan-Docs#1987]
I don't know where to make this complaint, and I'm sorry for making it wrong and remember that it's not for a "complaint" but for a warning that maybe it's possible to solve it, but anyway, it's the second time I have memory problems on linux using vulkan. the log below is from ryujinx in a pr that added support for the MSAA option the funny thing is that it's only on linux with vulkan that I get this problem. I ran two programs on both windows and linux. on windows I run unreal engine 5 and I don't get a lack of memory crash and neither does ryujinx. now if I run the applications on a linux system I lack memory space that cannot be allocated. remembering that it's running one at a time of course. Anyway, I'm saving money for a gpu upgrade. but it would be interesting if linux had this optimization more. I don't know if it's Vulkan's fault or the penguin kernel-based systems themselves. but it would be interesting if we could use a little less memory like in windows if it uses little memory right? As I'm not an experienced dev I can just be talking nonsense so I'm sorry. yes i use 2gb vram.

00:00:25.800 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.ResultExtensions.ThrowOnError(Result result)
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map)
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map)
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.AllocateDeviceMemory(PhysicalDevice physicalDevice, MemoryRequirements requirements, MemoryPropertyFlags flags)
   at Ryujinx.Graphics.Vulkan.BufferManager.Create(VulkanRenderer gd, Int32 size, Boolean forConditionalRendering, Boolean deviceLocal)
   at Ryujinx.Graphics.Vulkan.TextureView.SetData(ReadOnlySpan`1 data, Int32 layer, Int32 level, Int32 layers, Int32 levels, Boolean singleSlice, Nullable`1 region)
   at Ryujinx.Graphics.Vulkan.TextureView.SetData(SpanOrArray`1 data)
   at Ryujinx.Graphics.Vulkan.Effects.SmaaPostProcessingEffect.Initialize()
   at Ryujinx.Graphics.Vulkan.Effects.SmaaPostProcessingEffect..ctor(VulkanRenderer renderer, Device device, Int32 quality)
   at Ryujinx.Graphics.Vulkan.Window.UpdateEffect()
   at Ryujinx.Graphics.Vulkan.Window.Present(ITexture texture, ImageCrop crop, Action swapBuffersCallback)
   at Ryujinx.Graphics.GAL.Multithreading.Commands.Window.WindowPresentCommand.Run(WindowPresentCommand& command, ThreadedRenderer threaded, IRenderer renderer)
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_31(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer)
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop)
   at Ryujinx.Ui.RendererWidgetBase.Render() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx/Ui/RendererWidgetBase.cs:line 429
   at System.Threading.Thread.StartCallback()
Unhandled exception. Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.ResultExtensions.ThrowOnError(Result result)
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map)
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map)
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.AllocateDeviceMemory(PhysicalDevice physicalDevice, MemoryRequirements requirements, MemoryPropertyFlags flags)
   at Ryujinx.Graphics.Vulkan.BufferManager.Create(VulkanRenderer gd, Int32 size, Boolean forConditionalRendering, Boolean deviceLocal)
   at Ryujinx.Graphics.Vulkan.TextureView.SetData(ReadOnlySpan`1 data, Int32 layer, Int32 level, Int32 layers, Int32 levels, Boolean singleSlice, Nullable`1 region)
   at Ryujinx.Graphics.Vulkan.TextureView.SetData(SpanOrArray`1 data)
   at Ryujinx.Graphics.Vulkan.Effects.SmaaPostProcessingEffect.Initialize()
   at Ryujinx.Graphics.Vulkan.Effects.SmaaPostProcessingEffect..ctor(VulkanRenderer renderer, Device device, Int32 quality)
   at Ryujinx.Graphics.Vulkan.Window.UpdateEffect()
   at Ryujinx.Graphics.Vulkan.Window.Present(ITexture texture, ImageCrop crop, Action swapBuffersCallback)
   at Ryujinx.Graphics.GAL.Multithreading.Commands.Window.WindowPresentCommand.Run(WindowPresentCommand& command, ThreadedRenderer threaded, IRenderer renderer)
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_31(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer)
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop)
   at Ryujinx.Ui.RendererWidgetBase.Render() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx/Ui/RendererWidgetBase.cs:line 429
   at System.Threading.Thread.StartCallback()

**Comment by HansKristian-Work** [comment]
This sounds like an application issue that should be reported to the application you're using. There's nothing particularly actionable here for the Vulkan specification itself. What happens on "OutOfMemory" is highly GPU/driver/OS dependent and isn't really tied to APIs.

**Comment by HansKristian-Work** [comment]
Came up on call and we agreed to close this for reasons mentioned.
