### ISSUE TITLE
Unable to build pdf in Cygwin

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#464]
Following the readme and then using `make pdf` in Cygwin-64 gets me this:

```
$ make pdf
/home/Petr/.gem/ruby/gems/ruby-enum-0.7.1/lib/ruby-enum/enum.rb:34:in `const_set': asciidoctor: FAILED: /cygdrive/c/Dev/_GitHub/Vulkan-Docs/doc/specs/vulkan/vkspec.txt: Failed to load AsciiDoc document - wrong constant name default (NameError)
        from /home/Petr/.gem/ruby/gems/ruby-enum-0.7.1/lib/ruby-enum/enum.rb:34:in `define'
        from /home/Petr/.gem/ruby/gems/mathematical-1.6.7/lib/mathematical/configuration.rb:7:in `<class:Delimiters>'
        from /home/Petr/.gem/ruby/gems/mathematical-1.6.7/lib/mathematical/configuration.rb:4:in `<class:Configuration>'
        from /home/Petr/.gem/ruby/gems/mathematical-1.6.7/lib/mathematical/configuration.rb:3:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/Petr/.gem/ruby/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/Petr/.gem/ruby/gems/mathematical-1.6.7/lib/mathematical.rb:3:in `<top (required)>'
        from /home/Petr/.gem/ruby/gems/asciidoctor-mathematical-0.2.2/lib/asciidoctor-mathematical/extension.rb:23:in `process'
        from /home/Petr/.gem/ruby/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:479:in `[]'
        from /home/Petr/.gem/ruby/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:479:in `block in parse'
        from /home/Petr/.gem/ruby/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:478:in `each'
        from /home/Petr/.gem/ruby/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:478:in `parse'
        from /home/Petr/.gem/ruby/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1347:in `load'
        from /home/Petr/.gem/ruby/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1465:in `convert'
        from /home/Petr/.gem/ruby/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:95:in `block in invoke!'
        from /home/Petr/.gem/ruby/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `each'
        from /home/Petr/.gem/ruby/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `invoke!'
        from /home/Petr/.gem/ruby/gems/asciidoctor-1.5.5/bin/asciidoctor:14:in `<top (required)>'
        from /home/Petr/bin/asciidoctor:23:in `load'
        from /home/Petr/bin/asciidoctor:23:in `<main>'
make: *** [Makefile:174: /cygdrive/c/Dev/_GitHub/Vulkan-Docs/doc/specs/vulkan/../../../out/1.0/pdf/vkspec.pdf] Error 1

```

HTML target works fine...

**Comment by oddhack** [comment]
I haven't seen anything like that, but then I don't use Cygwin if I can possibly avoid it, either, and am about as far as one can possibly get from being a a Ruby expert. @TobiasHector might have seen that error before but otherwise, you may be on your own.

If you're able to try the Windows 10 Ubuntu subsystem I strongly recommend it over Cygwin. Uses normally Ubuntu/Debian packages and is much, much faster IME.

**Comment by krOoze** [comment]
@oddhack After reading `ruby-enum` changelog I found there something suspiciously similar to the error message. So, reverting to ruby-enum-0.7.0 fixed the problem. (Probably) nothing to do with the your scripts then... closing.

Consider adding a note to the readme for the meantime.
