### ISSUE TITLE
Build error: can't modify frozen Array (RuntimeError)

### ISSUE THREAD

**Issue by aurabindo** [KhronosGroup/Vulkan-Docs#476]
`make all` fails with the following message:

```
/home/aj/.rvm/gems/ruby-2.3.3/gems/prawn-templates-0.0.3/lib/prawn/templates.rb:246:in `<top (required)>': can't modify frozen Array (RuntimeError)
	from /home/aj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/aj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-pdf-1.5.0.alpha.14/lib/asciidoctor-pdf/converter.rb:10:in `<top (required)>'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-pdf-1.5.0.alpha.14/lib/asciidoctor-pdf.rb:3:in `require_relative'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-pdf-1.5.0.alpha.14/lib/asciidoctor-pdf.rb:3:in `<top (required)>'
	from /home/aj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /home/aj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /home/aj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/options.rb:219:in `block in parse!'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/options.rb:217:in `each'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/options.rb:217:in `parse!'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/options.rb:33:in `parse!'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:22:in `initialize'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-1.5.5/bin/asciidoctor:12:in `new'
	from /home/aj/.rvm/gems/ruby-2.3.3/gems/asciidoctor-1.5.5/bin/asciidoctor:12:in `<top (required)>'
	from /home/aj/.rvm/gems/ruby-2.3.3/bin/asciidoctor:22:in `load'
	from /home/aj/.rvm/gems/ruby-2.3.3/bin/asciidoctor:22:in `<main>'
	from /home/aj/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/aj/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
make: *** [Makefile:174: /run/media/aj/Buffer/git-clones/Vulkan-Docs/doc/specs/vulkan/../../../out/1.0/pdf/vkspec.pdf] Error 1
```

What could be the reason ?

**Comment by oddhack** [comment]
Is this on MacOS? Someone in Khronos reported a similar problem there. Unfortunately the spec editors have no ability to diagnose it, not being Mac users, and the errors suggest the problem is in one of the components like asciidoctor-mathematical or asciidoctor-pdf. You might try filing a report on those github repos and seeing if they have any suggestions.

**Comment by TobiasHector** [comment]
I did diagnose it Jon, did you not see my response with the fix? Here's what I discovered:

Basically, a new version of Prawn has broken particular usage of the prawn-template gem, which Asciidoctor-PDF relied on. See:

https://github.com/prawnpdf/prawn-templates/issues/14
https://github.com/asciidoctor/asciidoctor-pdf/issues/775

The TL;DR is that you should manually downgrade your version of Prawn until a fix is pushed to asciidoctor-pdf. If you've only got the one version of prawn installed, you can use:

```
gem uninstall prawn
gem install prawn -v 2.1.0
```

**Comment by oddhack** [comment]
@TobiasHector your last comment on the internal issue did not mention this. You may have said something in email which I didn't recall seeing. Sounds like both issues can be closed then, once the README.adoc is updated.

**Comment by bvogel** [comment]
Please update prawn to 2.2.1 and prawn-templates to 0.0.5 that will fix this issue.

**Comment by aurabindo** [comment]
Thank you all
